# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TOFMSDataAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TOFMSDataAnalysis(object):
    def setupUi(self, TOFMSDataAnalysis):
        TOFMSDataAnalysis.setObjectName("TOFMSDataAnalysis")
        TOFMSDataAnalysis.resize(266, 781)
        self.centralwidget = QtWidgets.QWidget(TOFMSDataAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.alphaValues = QtWidgets.QTextEdit(self.centralwidget)
        self.alphaValues.setGeometry(QtCore.QRect(20, 30, 231, 21))
        self.alphaValues.setObjectName("alphaValues")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 16))
        self.label.setObjectName("label")
        self.numberOfIons = QtWidgets.QTextEdit(self.centralwidget)
        self.numberOfIons.setGeometry(QtCore.QRect(20, 80, 231, 21))
        self.numberOfIons.setObjectName("numberOfIons")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 201, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 211, 16))
        self.label_3.setObjectName("label_3")
        self.isotopeMappings = QtWidgets.QTextEdit(self.centralwidget)
        self.isotopeMappings.setGeometry(QtCore.QRect(20, 140, 231, 131))
        self.isotopeMappings.setObjectName("isotopeMappings")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 290, 211, 16))
        self.label_4.setObjectName("label_4")
        self.rateMinimum = QtWidgets.QTextEdit(self.centralwidget)
        self.rateMinimum.setGeometry(QtCore.QRect(20, 310, 231, 21))
        self.rateMinimum.setObjectName("rateMinimum")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 340, 211, 16))
        self.label_5.setObjectName("label_5")
        self.rateMaximum = QtWidgets.QTextEdit(self.centralwidget)
        self.rateMaximum.setGeometry(QtCore.QRect(20, 360, 231, 21))
        self.rateMaximum.setObjectName("rateMaximum")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 400, 231, 16))
        self.label_6.setObjectName("label_6")
        self.nominalMasses = QtWidgets.QTextEdit(self.centralwidget)
        self.nominalMasses.setGeometry(QtCore.QRect(20, 420, 231, 21))
        self.nominalMasses.setObjectName("nominalMasses")
        self.computeValues = QtWidgets.QPushButton(self.centralwidget)
        self.computeValues.setGeometry(QtCore.QRect(40, 670, 191, 32))
        self.computeValues.setObjectName("computeValues")
        self.sisFilePath = QtWidgets.QTextEdit(self.centralwidget)
        self.sisFilePath.setGeometry(QtCore.QRect(20, 480, 221, 21))
        self.sisFilePath.setObjectName("sisFilePath")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 460, 201, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 510, 201, 16))
        self.label_8.setObjectName("label_8")
        self.signalFilePath = QtWidgets.QTextEdit(self.centralwidget)
        self.signalFilePath.setGeometry(QtCore.QRect(20, 530, 221, 21))
        self.signalFilePath.setObjectName("signalFilePath")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 560, 201, 16))
        self.label_9.setObjectName("label_9")
        self.cacheFileLocation = QtWidgets.QTextEdit(self.centralwidget)
        self.cacheFileLocation.setGeometry(QtCore.QRect(20, 580, 221, 21))
        self.cacheFileLocation.setObjectName("cacheFileLocation")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 610, 201, 16))
        self.label_10.setObjectName("label_10")
        self.outputFilePath = QtWidgets.QTextEdit(self.centralwidget)
        self.outputFilePath.setGeometry(QtCore.QRect(20, 630, 221, 21))
        self.outputFilePath.setObjectName("outputFilePath")
        self.loadJSON = QtWidgets.QPushButton(self.centralwidget)
        self.loadJSON.setGeometry(QtCore.QRect(40, 700, 191, 32))
        self.loadJSON.setObjectName("loadJSON")
        TOFMSDataAnalysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TOFMSDataAnalysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 266, 24))
        self.menubar.setObjectName("menubar")
        TOFMSDataAnalysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TOFMSDataAnalysis)
        self.statusbar.setObjectName("statusbar")
        TOFMSDataAnalysis.setStatusBar(self.statusbar)

        self.retranslateUi(TOFMSDataAnalysis)
        QtCore.QMetaObject.connectSlotsByName(TOFMSDataAnalysis)

    def retranslateUi(self, TOFMSDataAnalysis):
        _translate = QtCore.QCoreApplication.translate
        TOFMSDataAnalysis.setWindowTitle(_translate("TOFMSDataAnalysis", "TOFMS Data Analysis"))
        self.label.setText(_translate("TOFMSDataAnalysis", "Alpha Values (Comma Seperated)"))
        self.label_2.setText(_translate("TOFMSDataAnalysis", "Number of Ions"))
        self.label_3.setText(_translate("TOFMSDataAnalysis", "Isotop Mappings"))
        self.label_4.setText(_translate("TOFMSDataAnalysis", "Rate Minimum"))
        self.label_5.setText(_translate("TOFMSDataAnalysis", "Rate Maximum"))
        self.label_6.setText(_translate("TOFMSDataAnalysis", "Nominal Masses (Comma Seperated)"))
        self.computeValues.setText(_translate("TOFMSDataAnalysis", "Compute Critical Values"))
        self.label_7.setText(_translate("TOFMSDataAnalysis", "SIS File Path"))
        self.label_8.setText(_translate("TOFMSDataAnalysis", "Signal File Path"))
        self.label_9.setText(_translate("TOFMSDataAnalysis", "Cache File Location"))
        self.label_10.setText(_translate("TOFMSDataAnalysis", "Output File Path"))
        self.loadJSON.setText(_translate("TOFMSDataAnalysis", "Load and Compute"))

